"""Integration tests for datamine.py extract-all command."""

import json
import os
import struct
import sys
from typing import List, Tuple

import pytest

from util.datamining.package_reader import DBPF_MAGIC, DBPF_HEADER_SIZE
from util.datamining.resource_types import (
    COMBINED_TUNING_TYPE_ID,
    STRING_TABLE_TYPE_ID,
    DDS_TYPE_ID,
    PNG_TYPE_ID,
)
from util.datamining.string_table import STBL_MAGIC, STBL_HEADER_SIZE


# ---- Helpers ----

def build_test_package(resources):
    # type: (List[Tuple[int, int, int, bytes]]) -> bytes
    """Build a minimal DBPF v2.0 .package file in memory."""
    data_blocks = []
    data_offset = DBPF_HEADER_SIZE
    entry_info = []

    for type_id, group, instance, data in resources:
        entry_info.append((type_id, group, instance, data_offset, len(data)))
        data_blocks.append(data)
        data_offset += len(data)

    index_offset = data_offset
    index_flags = 0
    index_data = struct.pack("<I", index_flags)

    for type_id, group, instance, offset, size in entry_info:
        instance_hi = (instance >> 32) & 0xFFFFFFFF
        instance_lo = instance & 0xFFFFFFFF
        index_data += struct.pack("<IIIIIIIBB",
                                 type_id, group, instance_hi, instance_lo,
                                 offset, size, size, 0, 0)
        index_data += b'\x00\x00'

    index_size = len(index_data)

    header = bytearray(DBPF_HEADER_SIZE)
    header[0:4] = DBPF_MAGIC
    struct.pack_into("<I", header, 4, 2)
    struct.pack_into("<I", header, 8, 1)
    struct.pack_into("<I", header, 36, len(resources))
    struct.pack_into("<I", header, 60, index_size)
    struct.pack_into("<I", header, 64, index_offset)

    return bytes(header) + b"".join(data_blocks) + index_data


def build_stbl(entries):
    """Build a minimal STBL binary blob."""
    encoded = [(k, s.encode("utf-8")) for k, s in entries]
    string_data_len = sum(len(b) for _, b in encoded)

    header = STBL_MAGIC
    header += struct.pack("<H", 5)
    header += struct.pack("<B", 0)
    header += struct.pack("<Q", len(entries))
    header += struct.pack("<H", 0)
    header += struct.pack("<I", string_data_len)

    body = b""
    for key_hash, string_bytes in encoded:
        body += struct.pack("<I", key_hash)
        body += struct.pack("<B", 0)
        body += struct.pack("<H", len(string_bytes))
        body += string_bytes

    return header + body


# Minimal CombinedTuning XML with references
COMBINED_TUNING_XML = b"""\
<?xml version="1.0" encoding="utf-8"?>
<combined>
  <g s="merged">
    <E x="0">MAJOR</E>
  </g>
  <R>
    <I c="Skill" i="statistic" m="statistics.skill" n="skill_Cooking" s="16700">
      <r n="skill_level_type" x="0" />
      <T n="stat_name">0x1234ABCD</T>
    </I>
    <I c="Career" i="career" m="careers.career_tuning" n="career_Astronaut" s="25000">
      <T n="career_name">0xCCCCDDDD</T>
    </I>
  </R>
</combined>
"""

# A second CombinedTuning (delta) that overrides skill_Cooking
COMBINED_TUNING_DELTA = b"""\
<?xml version="1.0" encoding="utf-8"?>
<combined>
  <g s="merged"></g>
  <R>
    <I c="Skill" i="statistic" m="statistics.skill" n="skill_Cooking" s="16700">
      <T n="skill_level_type">MINOR</T>
      <T n="stat_name">0x1234ABCD</T>
    </I>
  </R>
</combined>
"""

# Valid 1x1 red PNG generated by Pillow
MINIMAL_PNG = (
    b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x01\x00\x00\x00\x01'
    b'\x08\x02\x00\x00\x00\x90wS\xde\x00\x00\x00\x0cIDATx\x9cc\xf8\xcf\xc0'
    b'\x00\x00\x03\x01\x01\x00\xc9\xfe\x92\xef\x00\x00\x00\x00IEND\xaeB`\x82'
)


def _setup_game_folder(tmp_path):
    """Create a mock game folder with test packages."""
    gf = str(tmp_path / "game")

    # Full simulation build with CombinedTuning
    sim_dir = os.path.join(gf, "Data", "Simulation")
    os.makedirs(sim_dir, exist_ok=True)

    full_pkg = build_test_package([
        (COMBINED_TUNING_TYPE_ID, 0, 1, COMBINED_TUNING_XML),
    ])
    with open(os.path.join(sim_dir, "SimulationFullBuild0.package"), "wb") as f:
        f.write(full_pkg)

    # Delta simulation build (overrides skill_Cooking)
    delta_pkg = build_test_package([
        (COMBINED_TUNING_TYPE_ID, 0, 1, COMBINED_TUNING_DELTA),
    ])
    with open(os.path.join(sim_dir, "SimulationDeltaBuild0.package"), "wb") as f:
        f.write(delta_pkg)

    # String table
    client_dir = os.path.join(gf, "Data", "Client")
    os.makedirs(client_dir, exist_ok=True)

    stbl_data = build_stbl([
        (0x1234ABCD, "Cooking"),
        (0xCCCCDDDD, "Astronaut"),
    ])
    strings_pkg = build_test_package([
        (STRING_TABLE_TYPE_ID, 0x00000000, 100, stbl_data),
    ])
    with open(os.path.join(client_dir, "Strings_ENG_US.package"), "wb") as f:
        f.write(strings_pkg)

    # Client package with a PNG image
    client_pkg = build_test_package([
        (PNG_TYPE_ID, 0, 0xAABBCCDD, MINIMAL_PNG),
    ])
    with open(os.path.join(client_dir, "ClientFullBuild0.package"), "wb") as f:
        f.write(client_pkg)

    return gf


class TestExtractAllDefaults:
    """Test extract-all with no --types (default: tuning + strings + images)."""

    def test_creates_output_directory(self, tmp_path):
        gf = _setup_game_folder(tmp_path)
        output = str(tmp_path / "output")

        from datamine import cmd_extract_all
        import argparse
        args = argparse.Namespace(
            game_folder=gf, output=output, types=None
        )
        cmd_extract_all(args)

        assert os.path.isdir(output)

    def test_extracts_tuning_xml(self, tmp_path):
        gf = _setup_game_folder(tmp_path)
        output = str(tmp_path / "output")

        from datamine import cmd_extract_all
        import argparse
        args = argparse.Namespace(
            game_folder=gf, output=output, types=None
        )
        cmd_extract_all(args)

        # Check XML files exist organized by class
        skill_file = os.path.join(output, "xml", "Skill", "skill_Cooking.xml")
        career_file = os.path.join(output, "xml", "Career", "career_Astronaut.xml")
        assert os.path.isfile(skill_file)
        assert os.path.isfile(career_file)

    def test_tuning_references_resolved(self, tmp_path):
        gf = _setup_game_folder(tmp_path)
        output = str(tmp_path / "output")

        from datamine import cmd_extract_all
        import argparse
        args = argparse.Namespace(
            game_folder=gf, output=output, types=None
        )
        cmd_extract_all(args)

        skill_file = os.path.join(output, "xml", "Skill", "skill_Cooking.xml")
        with open(skill_file, "r") as f:
            content = f.read()

        # Delta overrides full, so we should see MINOR not MAJOR
        assert "MINOR" in content
        assert "<r " not in content  # no unresolved references

    def test_delta_overrides_full(self, tmp_path):
        """Delta build should override the full build for same instance ID."""
        gf = _setup_game_folder(tmp_path)
        output = str(tmp_path / "output")

        from datamine import cmd_extract_all
        import argparse
        args = argparse.Namespace(
            game_folder=gf, output=output, types=None
        )
        cmd_extract_all(args)

        skill_file = os.path.join(output, "xml", "Skill", "skill_Cooking.xml")
        with open(skill_file, "r") as f:
            content = f.read()

        # Delta has MINOR, full has MAJOR — delta should win
        assert "MINOR" in content

    def test_extracts_strings(self, tmp_path):
        gf = _setup_game_folder(tmp_path)
        output = str(tmp_path / "output")

        from datamine import cmd_extract_all
        import argparse
        args = argparse.Namespace(
            game_folder=gf, output=output, types=None
        )
        cmd_extract_all(args)

        strings_file = os.path.join(output, "strings.json")
        assert os.path.isfile(strings_file)

        with open(strings_file, "r") as f:
            strings = json.load(f)

        assert "0x1234ABCD" in strings
        assert strings["0x1234ABCD"] == "Cooking"
        assert "0xCCCCDDDD" in strings
        assert strings["0xCCCCDDDD"] == "Astronaut"

    def test_extracts_images(self, tmp_path):
        gf = _setup_game_folder(tmp_path)
        output = str(tmp_path / "output")

        from datamine import cmd_extract_all
        import argparse
        args = argparse.Namespace(
            game_folder=gf, output=output, types=None
        )
        cmd_extract_all(args)

        images_dir = os.path.join(output, "images")
        assert os.path.isdir(images_dir)

        # Check the PNG was extracted with hex instance ID filename
        expected_file = os.path.join(images_dir, "00000000aabbccdd.png")
        assert os.path.isfile(expected_file)

        # Verify it's a valid PNG
        with open(expected_file, "rb") as f:
            magic = f.read(4)
        assert magic == b'\x89PNG'


class TestExtractAllTypesFilter:
    """Test --types filtering."""

    def test_types_stbl_only(self, tmp_path):
        gf = _setup_game_folder(tmp_path)
        output = str(tmp_path / "output")

        from datamine import cmd_extract_all
        import argparse
        args = argparse.Namespace(
            game_folder=gf, output=output, types=["STBL"]
        )
        cmd_extract_all(args)

        # Strings should be extracted
        assert os.path.isfile(os.path.join(output, "strings.json"))
        # Tuning and images should NOT be extracted
        assert not os.path.isdir(os.path.join(output, "xml"))
        assert not os.path.isdir(os.path.join(output, "images"))

    def test_types_png_only(self, tmp_path):
        gf = _setup_game_folder(tmp_path)
        output = str(tmp_path / "output")

        from datamine import cmd_extract_all
        import argparse
        args = argparse.Namespace(
            game_folder=gf, output=output, types=["PNG"]
        )
        cmd_extract_all(args)

        # Images should be extracted
        assert os.path.isdir(os.path.join(output, "images"))
        # Tuning and strings should NOT be extracted
        assert not os.path.isdir(os.path.join(output, "xml"))
        assert not os.path.isfile(os.path.join(output, "strings.json"))

    def test_types_raw_hex(self, tmp_path):
        """Specifying an unknown hex type should do raw extraction."""
        gf = _setup_game_folder(tmp_path)
        output = str(tmp_path / "output")

        # Add a package with a custom type
        custom_type = 0xDEADBEEF
        custom_data = b"custom resource data"
        pkg = build_test_package([(custom_type, 0, 42, custom_data)])

        # Write it as a package in the game folder
        custom_dir = os.path.join(gf, "Data", "Client")
        with open(os.path.join(custom_dir, "ClientFullBuild1.package"), "wb") as f:
            f.write(pkg)

        from datamine import cmd_extract_all
        import argparse
        args = argparse.Namespace(
            game_folder=gf, output=output, types=["0xDEADBEEF"]
        )
        cmd_extract_all(args)

        # Raw file should exist
        raw_dir = os.path.join(output, "DEADBEEF")
        assert os.path.isdir(raw_dir)
        files = os.listdir(raw_dir)
        assert len(files) == 1
        with open(os.path.join(raw_dir, files[0]), "rb") as f:
            assert f.read() == custom_data

    def test_types_all(self, tmp_path):
        """--types all should extract everything."""
        gf = _setup_game_folder(tmp_path)
        output = str(tmp_path / "output")

        from datamine import cmd_extract_all
        import argparse
        args = argparse.Namespace(
            game_folder=gf, output=output, types=["all"]
        )
        cmd_extract_all(args)

        # All smart types should be extracted
        assert os.path.isdir(os.path.join(output, "xml"))
        assert os.path.isfile(os.path.join(output, "strings.json"))
        assert os.path.isdir(os.path.join(output, "images"))
